-- workOutBackend schema (Neon Postgres)
-- All ids are UUIDs generated by the client (so offline-created rows have stable ids).
-- Soft deletes via deleted_at. Last-write-wins by updated_at.

create extension if not exists "pgcrypto";

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  username text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists workout_plans (
  id uuid primary key,
  user_id uuid not null references users(id) on delete cascade,
  name text not null,
  split_type text[] not null,
  days_per_week int not null,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists workout_plans_user_updated_idx on workout_plans (user_id, updated_at);

create table if not exists workout_days (
  id uuid primary key,
  plan_id uuid not null references workout_plans(id) on delete cascade,
  user_id uuid not null references users(id) on delete cascade,
  day_index int not null,
  day_type_name text[] not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists workout_days_user_updated_idx on workout_days (user_id, updated_at);

create table if not exists exercises (
  id uuid primary key,
  workout_day_id uuid not null references workout_days(id) on delete cascade,
  user_id uuid not null references users(id) on delete cascade,
  name text not null,
  set_number int not null,
  number_of_reps int not null,
  weight numeric not null default 0,
  targated_muscles text[] not null default '{}',
  is_the_exercise_on boolean not null default false,
  is_the_exercise_done boolean not null default false,
  is_body_weighted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists exercises_user_updated_idx on exercises (user_id, updated_at);
create index if not exists exercises_day_idx on exercises (workout_day_id);

create table if not exists profiles (
  user_id uuid primary key references users(id) on delete cascade,
  name text,
  age int,
  height numeric,
  weight numeric,
  gender text,
  current_goal text,
  updated_at timestamptz not null default now()
);
